/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "C:\\Users\\Administrator\\Desktop\\新建文件夹\\新建文件夹\\23 - 个人博客\\my-blog\\node_modules\\@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"
import m1 from "C:\\Users\\Administrator\\Desktop\\新建文件夹\\新建文件夹\\23 - 个人博客\\my-blog\\node_modules\\@vuepress\\plugin-active-header-links\\clientRootMixin.js"
import m2 from "C:\\Users\\Administrator\\Desktop\\新建文件夹\\新建文件夹\\23 - 个人博客\\my-blog\\node_modules\\@vuepress\\plugin-nprogress\\clientRootMixin.js"

export default [
  m0,
  m1,
  m2
]