/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\Administrator\\Desktop\\新建文件夹\\新建文件夹\\23 - 个人博客\\my-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-1b484072",
    path: "/articles/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b484072").then(next)
    },
  },
  {
    path: "/articles/index.html",
    redirect: "/articles/"
  },
  {
    name: "v-3ab3a4c4",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3ab3a4c4").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-392fc167",
    path: "/learning/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-392fc167").then(next)
    },
  },
  {
    path: "/learning/index.html",
    redirect: "/learning/"
  },
  {
    name: "v-a7db56f2",
    path: "/practice/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a7db56f2").then(next)
    },
  },
  {
    path: "/practice/index.html",
    redirect: "/practice/"
  },
  {
    name: "v-d0920232",
    path: "/together/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d0920232").then(next)
    },
  },
  {
    path: "/together/index.html",
    redirect: "/together/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]