/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "PG-bolg",
  "description": "蔡徐坤的博客",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "这是文章页面",
      "frontmatter": {},
      "regularPath": "/articles/",
      "relativePath": "articles/README.md",
      "key": "v-1b484072",
      "path": "/articles/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/timg.jp.jpg",
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。",
            "footer": "MIT Licensed | Copyright © 2018-present Evan You"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3ab3a4c4",
      "path": "/"
    },
    {
      "title": "这是学习路线",
      "frontmatter": {},
      "regularPath": "/learning/",
      "relativePath": "learning/README.md",
      "key": "v-392fc167",
      "path": "/learning/"
    },
    {
      "title": "这是项目实践",
      "frontmatter": {},
      "regularPath": "/practice/",
      "relativePath": "practice/README.md",
      "key": "v-a7db56f2",
      "path": "/practice/"
    },
    {
      "title": "这是一起学习",
      "frontmatter": {},
      "regularPath": "/together/",
      "relativePath": "together/README.md",
      "key": "v-d0920232",
      "path": "/together/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "学习路线",
        "link": "/learning/"
      },
      {
        "text": "项目实战",
        "link": "/practice/"
      },
      {
        "text": "零散文章",
        "link": "/articles/"
      },
      {
        "text": "一起学习",
        "link": "/together/"
      },
      {
        "text": "github",
        "link": "https://github.com/PGthirteen"
      }
    ]
  }
}